# Generated by Django 5.1.6 on 2025-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("error", "Error"),
                            ("skip", "Skip"),
                        ],
                        default="pass",
                        max_length=10,
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="testilogger_status_e8328b_idx"
                    ),
                    models.Index(
                        fields=["executed_at"], name="testilogger_execute_01f1b6_idx"
                    ),
                ],
            },
        ),
    ]
